spring:
  security:
    user:
      name: user
      password: # Leave blank to auto-generate

  application:
    name: hogwarts-artifacts-online
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true

server:
  port: 8089

api:
  endpoint:
    base-url: /api/v1